/**
 * Par times (seconds) per region: the route bot's verified time over the main route.
 * Generated by tools/par_times.ts — do not edit by hand; regenerate after changing a region.
 */
export const PAR_TIMES: readonly number[] = [111.9, 107.7, 114.6, 129.6, 100.2, 111.9, 61.3, 88.7, 60.3, 34.5];
